#!/usr/bin/env python3
"""Create the raw-data reanalysis version of the Frontiers manuscript."""
from pathlib import Path
from docx import Document
import csv
from collections import defaultdict

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / "outputs" / "Frontiers_submission_package" / "Manuscript_Frontiers_Inflammation.docx"
TARGET = ROOT.parent / "outputs" / "Frontiers_submission_package" / "Manuscript_Frontiers_Inflammation_revised_raw_reanalysis.docx"

doc = Document(SOURCE)
p = doc.paragraphs

updates = {
0: "Raw-data transcriptomic reanalysis and genetic sensitivity analyses define an expression-associated myeloid injury program in human intracerebral hemorrhage",
7: "Figures: 8 main and 7 supplementary; Tables: 0 main and 9 supplementary.",
8: "Keywords: intracerebral hemorrhage; raw-data reanalysis; Mendelian randomization; colocalization; single-cell RNA sequencing; myeloid cells; reproducibility",
10: ("Background: Secondary injury after intracerebral hemorrhage (ICH) involves inflammatory, hypoxic, and iron-handling responses, but expression changes do not by themselves establish causal regulators. Methods: We reprocessed the principal GEO cohorts from their deposited raw data: GSE24265 Affymetrix CEL files by robust multi-array averaging and patient-blocked limma; GSE163256 raw RNA-sequencing counts by technical-replicate collapse and patient-blocked edgeR/voom; and GSE266873 raw 10x matrices by sample-level single-cell quality control, marker-module annotation, and pseudobulk analysis. We re-ran cis-eQTL Mendelian randomization (MR) against FinnGen R10 I9_ICH after 1000 Genomes European LD clumping, reported instrument strength, Steiger directionality, heterogeneity and pleiotropy estimability, controlled four-gene testing by Benjamini-Hochberg correction, and performed regional colocalization where exposure data were available. Results: In GSE24265, HMOX1, STAT3, and NLRP3 were nominally altered but none passed transcriptome-wide false-discovery-rate correction; TLR4 was not differentially expressed. In GSE163256, HMOX1, STAT3, and NLRP3 were increased and TLR4 was modestly decreased, with directions concordant between cohorts. LD clumping retained one strong instrument per gene (F=288-5,177), making Cochran heterogeneity, MR-Egger pleiotropy, and leave-one-out analyses non-estimable. No MR association survived correction (minimum FDR=0.265), and available NLRP3 and TLR4 colocalization analyses showed low shared-signal posterior probabilities. Conclusions: The raw-data reanalysis supports an expression- and cell-state-associated injury program but does not establish any of the four genes as a causal therapeutic target. TLR4 and STAT3 are retained only as genetically prioritized candidate regulators requiring independent validation; HMOX1 and NLRP3 are downstream candidates associated with expression and cellular state."),
15: ("We therefore re-evaluated the main GEO cohorts from deposited raw files and separated three evidentiary layers: differential expression, cellular localization/state, and genetic causal prioritization. The study was designed to identify reproducible signals while explicitly preventing expression-level prominence or pathway membership from being interpreted as proof of causality or therapeutic efficacy."),
18: ("The primary datasets were GSE24265 (paired perihematomal and contralateral Affymetrix profiles), GSE163256 (longitudinal human myeloid RNA sequencing), and GSE266873 (nine raw 10x single-cell matrices spanning early, intermediate, and later post-ICH sampling). Each was reconstructed from the original GEO deposits rather than from previously exported analysis tables. GSE166638 and GSE125512 were retained only as contextual datasets and were not used to claim primary replication. Accession identifiers, download URLs, file checksums, sample maps, intermediate matrices, and session information are included in the accompanying reproducibility archive."),
20: ("The hypoxia-ferroptosis coupling program was treated as a prespecified biological hypothesis rather than a validated causal module. Candidate-level reporting focused on TLR4, STAT3, HMOX1, and NLRP3. HMOX1 and NLRP3 were designated expression- and cell-state-associated downstream candidates; TLR4 and STAT3 were designated genetically prioritized candidate regulators only, subject to the corrected MR and colocalization results below."),
22: ("For GSE24265, all 11 raw CEL files were normalized jointly by robust multi-array averaging. Probe sets were mapped to gene symbols, and differential expression was estimated with limma using patient blocking for paired perihematomal-versus-contralateral samples. For GSE163256, raw feature counts and GEO sample metadata were reconstructed, technical replicates were summed, lowly expressed genes were filtered, library sizes were normalized, and patient-blocked contrasts were fitted with edgeR/voom. Benjamini-Hochberg false discovery rates (FDRs) were calculated within each transcriptome-wide analysis. Candidate results were extracted only after the full models had been fitted."),
24: ("Candidate interpretation was based on complete raw-data differential-expression results, cross-cohort directionality, prespecified biological relevance, and the separately conducted genetic analyses. Pathway enrichment or recurrence was used for biological description only and was not treated as proof that a gene was upstream, causal, or therapeutically actionable."),
26: ("Exposure instruments were the previously prespecified blood cis-eQTL candidates, while outcome associations were re-extracted from FinnGen release 10 phenotype I9_ICH (4,056 cases and 371,717 controls). Variants were harmonized by effect allele and clumped against the 1000 Genomes European reference at r2<0.001 within 500 kb. Instrument strength was quantified as F=(beta_exposure/se_exposure)^2. With one retained variant per gene, the Wald ratio was the appropriate estimator; Cochran Q, MR-Egger intercept, and leave-one-out sensitivity analyses were reported as mathematically non-estimable rather than being imputed. Steiger directionality compared variance explained in exposure and outcome, using the FinnGen effect-allele frequency as a documented proxy where exposure allele frequency was unavailable. Four-gene MR P values were controlled by the Benjamini-Hochberg method."),
28: ("Regional colocalization was performed by approximate Bayes factors using raw cis-eQTL Catalogue whole-blood associations and FinnGen I9_ICH summary statistics within +/-1 Mb of each gene. Default priors were p1=1e-4, p2=1e-4, and p12=1e-5, with p12 sensitivity analyses at 1e-6 and 1e-4. Analyses were declared non-estimable when the selected exposure dataset contained no regional variants. GSE266873 raw 10x matrices were processed independently per sample, filtered at 200-6,000 detected features, at least 500 counts, and less than 20% mitochondrial reads, then normalized and clustered in Seurat. Major cell classes were assigned using prespecified marker modules. Differential expression used sample-by-cell-type pseudobulk counts with edgeR quasi-likelihood models, thereby treating biological samples rather than individual cells as replicates."),
30: ("All tests were two-sided. Transcriptome-wide differential-expression and four-gene MR analyses used Benjamini-Hochberg FDR correction. Effect estimates are reported on their native scales with 95% confidence intervals. In Figure 4A, the horizontal axis is the log-odds effect estimate and may therefore contain negative values; odds ratios, when reported in text or tables, are exponentiated and strictly positive. Single-variant MR diagnostics that require multiple independent instruments were designated non-estimable."),
33: ("Raw deposits were successfully reconstructed for the two principal bulk cohorts and the primary single-cell cohort. The workflow records accession-level provenance, sample mappings, pre- and post-quality-control data, complete gene-level model outputs, source data for revised figures, package versions, session information, and SHA-256 checksums. Thus, candidate-level conclusions below arise from newly fitted models rather than from extraction of previously exported result tables."),
35: ("In the paired GSE24265 analysis, HMOX1 (log2 fold change 2.188, P=0.00115, FDR=0.204), STAT3 (3.135, P=0.0179, FDR=0.315), and NLRP3 (1.480, P=0.0262, FDR=0.349) were nominally increased, whereas TLR4 was unchanged (-0.064, P=0.910, FDR=0.980). None of these four candidates passed transcriptome-wide FDR correction in this small discovery cohort. The result supports cautious hypothesis generation but not a claim of validated differential expression for any individual candidate."),
37: ("Reanalysis of the complete GSE163256 raw count matrix, after mapping 399 sequencing columns and collapsing technical replicates to 274 biological sample-by-cell-type-by-time combinations, identified higher HMOX1 (log2 fold change 2.878, FDR=2.80x10^-69), STAT3 (0.566, FDR=4.93x10^-21), and NLRP3 (0.493, FDR=1.01x10^-4), with modestly lower TLR4 (-0.173, FDR=0.0320). Candidate directions were concordant with GSE24265, including the near-null/negative TLR4 estimate. These results demonstrate reproducible expression behavior across the fitted contrasts, not genetic causality."),
38: "Corrected genetic analyses do not confirm causal effects of the four candidates",
39: ("After 1000 Genomes European LD clumping, one independent cis-eQTL remained for each gene: rs133415 for HMOX1 (F=965), rs10754559 for NLRP3 (F=966), rs1053004 for STAT3 (F=288), and rs10491851 for TLR4 (F=5,177). Wald-ratio estimates were HMOX1 OR 1.188 (95% CI 0.858-1.644; FDR=0.598), NLRP3 OR 1.019 (0.790-1.313; FDR=0.887), STAT3 OR 0.644 (0.403-1.030; FDR=0.265), and TLR4 OR 0.985 (0.865-1.122; FDR=0.887). Steiger tests supported the exposure-to-outcome direction for all four instruments, but no association survived multiple testing. Because only one variant remained per gene, heterogeneity, MR-Egger horizontal-pleiotropy, and leave-one-out tests were non-estimable. These corrected results do not validate TLR4, STAT3, HMOX1, or NLRP3 as causal ICH targets."),
40: "Colocalization provides no evidence of a shared causal signal",
41: ("Whole-blood regional eQTL data were available for NLRP3 and TLR4. Under the default p12=1e-5 prior, the posterior probability of a shared causal variant was low for NLRP3 (PP.H4=0.0057) and TLR4 (PP.H4=0.0115); prior-sensitivity analyses did not support a robust shared signal. The selected exposure dataset contained no regional STAT3 or HMOX1 variants, so those comparisons were explicitly designated non-estimable. The combined MR and colocalization results reduce confidence that the observed expression associations represent a shared genetically causal mechanism."),
42: "Single-cell raw-data analysis localizes candidate expression without proving causal regulation",
43: ("The nine GSE266873 raw 10x matrices were jointly quality controlled and annotated using prespecified marker modules for microglia/macrophages, monocytes, neutrophils, T/NK cells, B cells, platelets, erythroid cells, and endothelial cells. Candidate expression and sample-level cell-type composition were quantified, and cell-type-specific comparisons used sample-level pseudobulk models. These analyses localize expression to cellular compartments and post-ICH states; they do not convert HMOX1 or NLRP3 into demonstrated causal nodes, nor do they establish TLR4 or STAT3 as validated therapeutic targets."),
44: "Expression and cellular-state findings are separated from causal inference",
45: ("Across bulk and single-cell layers, HMOX1 and NLRP3 are most defensibly interpreted as downstream candidates associated with expression and cellular state. Their biological plausibility in heme handling, oxidative stress, and inflammasome activity warrants experimental follow-up, but the present observational transcriptomic analyses cannot distinguish regulatory causation from cellular composition, injury severity, or response to the hematoma environment."),
46: "Exploratory communication and trajectory panels are not used as confirmatory evidence",
47: ("Previously exported trajectory and cell-cell communication panels were retained only as exploratory context and were excluded from the corrected causal argument because they were not reconstructed from the primary raw single-cell workflow reported here. No therapeutic or directional signaling claim in this revised manuscript depends on those exported panels."),
49: ("The principal result is a narrowing of inference. Raw-data reanalysis supports a reproducible expression-associated inflammatory and iron-handling response in human ICH, but the corrected genetic analyses do not identify a statistically supported causal regulator among TLR4, STAT3, HMOX1, and NLRP3. This distinction is essential because expression magnitude, pathway membership, and cell-type localization can reflect consequences of tissue injury or shifts in cellular composition."),
50: ("TLR4 and STAT3 should therefore be described as genetically prioritized candidate regulators, not validated therapeutic targets. Both had strong instruments and correct Steiger directionality, but neither survived four-gene correction, and the available TLR4 colocalization result did not support a shared causal variant. HMOX1 and NLRP3 remain expression- and cell-state-associated downstream candidates. Their strong transcriptional signals are biologically informative but do not establish them as upstream causal nodes."),
51: ("The single-cell analysis adds compartmental resolution while preserving this evidentiary boundary. Marker-module annotation and sample-level pseudobulk comparisons reduce cell-as-replicate bias, but cellular localization still cannot demonstrate that manipulating a candidate will alter ICH risk or outcome. Such a claim requires independent genetic replication, perturbation experiments, or both."),
52: ("Several limitations constrain interpretation. GSE24265 contains only 11 arrays and none of the four candidate genes passed transcriptome-wide FDR correction. GSE266873 contains three samples per time stratum, lacks a matched healthy-control arm, and uses marker-module rather than reference-mapping annotation; no dedicated doublet model was available in the deposited matrices. The exposure instruments were taken from the prespecified eQTL candidate rows used in the earlier analysis rather than from a complete genome-wide eQTLGen download. Clumping left only one instrument per gene, precluding heterogeneity and MR-Egger tests. Exposure allele frequencies were unavailable for Steiger testing and FinnGen frequencies were used as a transparent proxy. Finally, the selected whole-blood eQTL Catalogue dataset had regional data for NLRP3 and TLR4 but not STAT3 or HMOX1, limiting colocalization coverage."),
53: ("Accordingly, the study provides a reproducible candidate map rather than target validation. The supplied code and intermediate results permit the analyses to be independently rerun and extended with larger perihematomal cohorts, complete genome-wide exposure data, ancestry-matched LD reference panels, multi-instrument cis-MR, broader colocalization resources, and experimental perturbation."),
55: ("Raw-data reanalysis supports an expression- and cell-state-associated myeloid injury program in human ICH. Corrected LD-clumped MR and regional colocalization do not establish any evaluated gene as causal. TLR4 and STAT3 are genetically prioritized candidate regulators requiring independent validation, whereas HMOX1 and NLRP3 are downstream candidates associated with expression and cellular state. None should be described as an already validated therapeutic target on the basis of the present study."),
65: ("During revision, the authors used OpenAI Codex to assist with code drafting, execution orchestration, reproducibility packaging, figure formatting, and English-language editing. All analytical choices, data provenance, generated code, numerical outputs, and manuscript text were reviewed by the authors, who take full responsibility for the work. The accompanying repository package provides the complete executable record needed for independent verification."),
67: ("The raw datasets are publicly available from NCBI GEO under GSE24265, GSE163256, and GSE266873. Complete R code, acquisition helpers, sample maps, intermediate results, source data, environment records, and checksums are supplied with this revision in a release-ready repository archive. The public GitHub URL and Zenodo DOI will be inserted after authenticated deposition."),
69: ("The revised supplementary package includes complete raw-data differential-expression results, quality-control and sample-mapping tables, harmonized and clumped MR instruments, F statistics, Steiger results, multiple-testing-adjusted estimates, estimability statements for heterogeneity and pleiotropy analyses, colocalization outputs and prior sensitivity analyses, source data, and software-environment records."),
110: ("Figure 1. Corrected study design and evidence hierarchy. Principal GEO cohorts were reconstructed from raw deposits; expression, cellular localization, and genetic causal prioritization were analyzed as distinct evidentiary layers."),
111: ("Figure 2. Raw-data discovery analysis in GSE24265. Complete RMA and patient-blocked differential-expression results are reported; candidate-level nominal signals are not interpreted as transcriptome-wide significant."),
112: ("Figure 3. Raw-count reanalysis of GSE163256. Technical replicates were collapsed before patient-blocked modeling, and candidate estimates were extracted from the complete fitted transcriptome-wide model."),
113: ("Figure 4. Corrected genetic sensitivity analyses. A, Wald-ratio estimates after 1000 Genomes European LD clumping; the horizontal axis is the effect estimate on the log-odds scale and the dashed line denotes zero. B, posterior probability of a shared causal variant (PP.H4) for regional colocalization at the default p12=1e-5 prior; STAT3 and HMOX1 were non-estimable in the selected exposure dataset. The dashed line at PP.H4=0.8 is a visual reference, not a significance threshold used to select results."),
114: ("Figure 5. Expression-program summaries are presented as descriptive evidence and are not used to infer causal regulation."),
115: ("Figure 6. GSE266873 raw single-cell analysis. Major cell classes were assigned using prespecified marker modules after sample-level quality control; candidate localization is descriptive."),
116: ("Figure 7. Exploratory myeloid-state views. These panels are hypothesis-generating and are not used as confirmatory causal evidence."),
117: ("Figure 8. Exploratory communication views. Previously exported panels are retained as contextual material only and do not support target-validation claims."),
}

qc_path = ROOT / "results" / "tables" / "GSE266873_sample_qc_summary.tsv"
candidate_path = ROOT / "results" / "tables" / "GSE266873_candidate_expression.tsv"
pseudobulk_path = ROOT / "results" / "tables" / "GSE266873_pseudobulk_DE.tsv"
if qc_path.exists() and candidate_path.exists() and pseudobulk_path.exists():
    with qc_path.open(encoding="utf-8") as handle:
        qc_rows = list(csv.DictReader(handle, delimiter="\t"))
    before = sum(int(float(row["cells_before"])) for row in qc_rows)
    after = sum(int(float(row["cells_after"])) for row in qc_rows)

    values = {gene: defaultdict(list) for gene in ("TLR4", "STAT3", "HMOX1", "NLRP3")}
    with candidate_path.open(encoding="utf-8") as handle:
        for row in csv.DictReader(handle, delimiter="\t"):
            for gene in values:
                if row.get(gene) not in (None, "", "NA"):
                    values[gene][row["cell_type"]].append(float(row[gene]))
    top = {}
    for gene, by_type in values.items():
        means = {cell_type: sum(x) / len(x) for cell_type, x in by_type.items() if x}
        top[gene] = max(means, key=means.get) if means else "not detected"

    significant = []
    with pseudobulk_path.open(encoding="utf-8") as handle:
        for row in csv.DictReader(handle, delimiter="\t"):
            if row.get("gene") in values and row.get("FDR") not in (None, "", "NA"):
                if float(row["FDR"]) < 0.05:
                    significant.append(f"{row['gene']} in {row['cell_type']} ({row['contrast']})")
    sig_text = ("; ".join(significant[:6]) if significant else
                "none of the four candidates passed pseudobulk FDR correction")
    updates[43] = (
        f"The nine GSE266873 raw 10x matrices contained {before:,} cells before filtering and "
        f"{after:,} cells after the prespecified quality-control thresholds. Major classes were "
        "assigned with auditable marker-module scores, and sample-level pseudobulk models were "
        "used for inference. Mean normalized expression was highest in "
        f"{top['TLR4']} for TLR4, {top['STAT3']} for STAT3, {top['HMOX1']} for HMOX1, and "
        f"{top['NLRP3']} for NLRP3. Candidate-level pseudobulk testing showed {sig_text}. "
        "These findings localize expression to cellular compartments and post-ICH states; they "
        "do not establish causal regulation or therapeutic efficacy."
    )

for idx, text in updates.items():
    p[idx].text = text

TARGET.parent.mkdir(parents=True, exist_ok=True)
doc.save(TARGET)
print(TARGET)
